### ISSUE TITLE
Overlapping words

### ISSUE THREAD

**Issue by arnaudspotfire** [jacobsjan/WordCloud2#7] opened 2021-11-17 10:50 UTC
Hello,

When updated an existing word cloud (v1.0.4) to v1.0.5 I noticed an issue with some words overlapping.

![1 0 4](https://user-images.githubusercontent.com/15086293/142186918-238efa2d-35a5-4909-842c-859adb56be45.png)
![1 0 5](https://user-images.githubusercontent.com/15086293/142186960-cf309215-f9c8-429c-af51-fd366099129e.png)

**Comment by jacobsjan** [comment] 2021-12-20 13:49
Thanks for reporting this issue and the further clarification on the method used to upgrade from 1.0.4 to 1.0.5:

1.     Open v1.0.5 project in VS Code and build the project.
2.     Open an analysis which contains a word cloud (in 1.0.4).
3.     Enable development for mods in analysis (Tools > Development)
4.     Click the mods development button next to the Mod title and reload from development server

Still unable to reproduce it thought and it only seems to affect the rendering right after upgrading, not thereafter. So I'm closing this issue for the time being.

**Closed as completed by jacobsjan** 2021-12-20 13:49 UTC
